// Mock data for Investments page demo
export const mockProjects = [
  {
    id: "proj1",
    name: "Green Energy Farm",
    description: "A solar energy project to power rural communities sustainably.",
    sector: "renewable_energy",
    image: "/images/solar-farm.jpg",
  },
  {
    id: "proj2",
    name: "Halal Food Startup",
    description: "Expanding a chain of Sharia-compliant restaurants.",
    sector: "food_and_beverage",
    image: "/images/restaurant.jpg",
  },
  {
    id: "proj3",
    name: "Islamic Fintech App",
    description: "A mobile app for Sharia-compliant financial services.",
    sector: "fintech",
    image: "/images/fintech-app.jpg",
  },
  {
    id: "proj4",
    name: "Eco-Friendly Housing",
    description: "Affordable, sustainable housing for low-income families.",
    sector: "real_estate",
    image: "/images/eco-housing.jpg",
  },
  {
    id: "proj5",
    name: "Organic Farm Co-op",
    description: "Supporting local farmers with organic produce markets.",
    sector: "agriculture",
    image: "/images/organic-farm.jpg",
  },
  {
    id: "proj6",
    name: "Education Tech Platform",
    description: "Online learning platform for Islamic studies.",
    sector: "education",
    image: "/images/edtech.jpg",
  },
  {
    id: "proj7",
    name: "Healthcare Clinic",
    description: "Community clinic offering affordable healthcare services.",
    sector: "healthcare",
    image: "/images/clinic.jpg",
  },
  {
    id: "proj8",
    name: "Sustainable Fashion",
    description: "Ethical clothing line using eco-friendly materials.",
    sector: "fashion",
    image: "/images/fashion.jpg",
  },
  {
    id: "proj9",
    name: "Water Purification Plant",
    description: "Clean water solutions for underserved regions.",
    sector: "infrastructure",
    image: "/images/water-plant.jpg",
  },
  {
    id: "proj10",
    name: "Tech Incubator",
    description: "Supporting startups with Sharia-compliant funding.",
    sector: "technology",
    image: "/images/incubator.jpg",
  },
]

export const mockInvestments = [
  {
    id: "inv1",
    projectId: "proj1",
    amount: 5000,
    status: "accepted",
    createdAt: "2025-03-15T10:00:00Z",
  },
  {
    id: "inv2",
    projectId: "proj2",
    amount: 2500,
    status: "pending",
    createdAt: "2025-04-20T14:30:00Z",
  },
  {
    id: "inv3",
    projectId: "proj3",
    amount: 10000,
    status: "completed",
    createdAt: "2024-12-10T09:00:00Z",
  },
  {
    id: "inv4",
    projectId: "proj4",
    amount: 7500,
    status: "accepted",
    createdAt: "2025-01-25T16:45:00Z",
  },
  {
    id: "inv5",
    projectId: "proj5",
    amount: 3000,
    status: "rejected",
    createdAt: "2025-02-05T11:20:00Z",
  },
  {
    id: "inv6",
    projectId: "proj6",
    amount: 4500,
    status: "pending",
    createdAt: "2025-05-10T08:15:00Z",
  },
  {
    id: "inv7",
    projectId: "proj7",
    amount: 6000,
    status: "completed",
    createdAt: "2024-11-30T13:00:00Z",
  },
  {
    id: "inv8",
    projectId: "proj8",
    amount: 2000,
    status: "accepted",
    createdAt: "2025-03-01T15:30:00Z",
  },
  {
    id: "inv9",
    projectId: "proj9",
    amount: 8000,
    status: "rejected",
    createdAt: "2025-04-05T10:10:00Z",
  },
  {
    id: "inv10",
    projectId: "proj10",
    amount: 3500,
    status: "pending",
    createdAt: "2025-05-25T12:00:00Z",
  },
  {
    id: "inv11",
    projectId: "proj1",
    amount: 4000,
    status: "completed",
    createdAt: "2024-10-15T09:45:00Z",
  },
  {
    id: "inv12",
    projectId: "proj3",
    amount: 5500,
    status: "accepted",
    createdAt: "2025-02-20T14:00:00Z",
  },
]